name: Update Classes

on:
  workflow_dispatch:

jobs:
  classUpdate:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{steps.update.outputs.totalChanges > 0}}
      commitSha: ${{steps.commit.outputs.commit_long_sha}}

    steps:
      - uses: actions/checkout@v4
      - id: update
        uses: metro420yt/class-update@v1-rc
        with:
          folder: stuff
          ext: scss

      - uses: gha-utilities/sass-build@v0.6.0
        if: ${{steps.update.outputs.totalChanges > 0}}
        with:
          source: ./app.scss
          destination: ./betterdiscord/main.css
          outputStyle: expanded
      - uses: EndBug/add-and-commit@v9
        id: commit
        if: ${{steps.update.outputs.totalChanges > 0}}
        with:
          default_author: github_actions
          message: "chore: update classes"
          fetch: true

  build:
    needs: classUpdate
    if: ${{needs.classUpdate.outputs.changed == true}}
    uses: ./.github/workflows/gh-pages.yml
    with:
      sha: ${{needs.classUpdate.outputs.commitSha}}
