name: Update Classes

on:
  workflow_dispatch:
  repository_dispatch: #webhook trigger
    types: [update_class]

jobs:
  classUpdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: update
        uses: metro420yt/class-update@v1-rc
        with:
          folder: stuff
          ext: scss

      - uses: gha-utilities/sass-build@v0.6.0
        if: ${{steps.update.outputs.totalChanges > 0}}
        with:
          source: ./app.scss
          destination: ./betterdiscord/main.css
          outputStyle: expanded
      - uses: EndBug/add-and-commit@v9
        if: ${{steps.update.outputs.totalChanges > 0}}
        with:
          default_author: github_actions
          message: "chore: update classes"
          fetch: true
